// playground/react-example/src/App.tsx
import React from 'react'
import { Button } from '@kompkit/react'

export default function App() {
  return (
    <div style={{ padding: '2rem' }}>
      <h1>KompKit React Playground</h1>
      <Button>Default</Button>
      <Button variant="primary">Primary</Button>
      <Button variant="secondary">Secondary</Button>
    </div>
  )
}

// playground/vue-example/src/App.vue
<template>
    <div class="playground-container">
      <h1>KompKit Vue Playground</h1>
      <h2>Button Component</h2>
      <KButton variant="primary">Primary</KButton>
      <KButton variant="secondary">Secondary</KButton>
    </div>
  </template>
  
  <script setup>
  import { KButton } from '@kompkit/vue'
  </script>
